# pytoch dataloader file limit

In [2]:
# Unlimit the number of open files for pytorch dataloader
# do in the terminal: ulimit -n 65535
import torch
torch.multiprocessing.set_sharing_strategy('file_system')

# torch.view (reshape) 

In [1]:
import torch
x = torch.rand(2,12,512,4,4)
x2 = x.view([-1] + list(x.shape[2:]))
torch.equal(x[1,3], x2[12+3])

True

In [4]:
import torch
x = torch.rand(2,12,16,512)
x2 = x.view([x.shape[0], -1, x.shape[-1]])
x3 = x2.view(x.shape)
torch.equal(x3, x)

True

# Pointwise multiplication of minibatches

In [25]:
import torch
a = torch.randn(4, 512, 3, 3)
b = 2 * torch.ones(3, 3)
b[0,2] = 0

c = a*b
c2 = a*b.expand_as(a)
torch.equal(c, c2)

True

# Flip tensor 90, 180, 270 degrees

In [9]:
import torch
x = torch.zeros(1, 1, 4, 4)
k = 0.0
for i in range(4):
    for j in range(4):
        x[:, :, i, j] = k
        k += 1

x90 = x.transpose(2, 3).flip(2)
x180 = x.flip(2)
x270 = x.transpose(2, 3).flip(3)
print(x); print(x90); print(x180); print(x270)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[ 3.,  7., 11., 15.],
          [ 2.,  6., 10., 14.],
          [ 1.,  5.,  9., 13.],
          [ 0.,  4.,  8., 12.]]]])
tensor([[[[12., 13., 14., 15.],
          [ 8.,  9., 10., 11.],
          [ 4.,  5.,  6.,  7.],
          [ 0.,  1.,  2.,  3.]]]])
tensor([[[[12.,  8.,  4.,  0.],
          [13.,  9.,  5.,  1.],
          [14., 10.,  6.,  2.],
          [15., 11.,  7.,  3.]]]])
